### ISSUE TITLE
Lost License Form Sends Email With Bad Email

### ISSUE THREAD

**Issue by johnwu** [jkudish/JigoShop-Software-Add-on#3]
If I enter an email address that does not have any purchases, it currently sends an email. It should just display a message on the web page that no purchases were found. Also noticed that after pressing the "Email Now", the busy indicator just spins - would it be possible to display "Orders have been emailed to you at {email}" for success and "No purchases found" on failure?

**Comment by johnwu** [comment]
oh, I see I used XXXX@XXXXX.com, and there are orders that have not completed yet.

**Comment by jkudish** [comment]
> oh, I see I used XXXX@XXXXX.com, and there are orders that have not completed yet.

That may be the key to the issue here. I may have forgotten to put a condition for incomplete sales in the code that handles that part.

**Comment by johnwu** [comment]
Ok, if I use an email that has no orders, then it I get the no orders
found message. It is just XXXX@XXXXX.com, any ideas why my orders are
incomplete?

**Comment by jkudish** [comment]
I am looking into this issue now

**Comment by johnwu** [comment]
Here is the test product I used

http://secure.sparkbooth.com/store/buy-sparkbooth/test-product/

It is hooked into my real account.
